### ISSUE TITLE
UPR cards' `defaultImageName` isn't the same as other sets, as different in .tsv

### ISSUE THREAD

**Issue by LoveGlitchCoffee** [fabrary/fab-cards#12]
Example of names from others sets:
[**Blood on her Hands**](https://github.com/fabrary/fab-cards/blob/4bff9e1a47da60b84815dfe18e304faaf4123798/src/cards.tsv#L3406)

UPR example
[**Invoke Kyloria**](https://github.com/fabrary/fab-cards/blob/4bff9e1a47da60b84815dfe18e304faaf4123798/src/cards.tsv#L3922)

Unsure if it comes from `flesh-cube` itself, I assume it does?

**Comment by manwaring** [comment]
Hey @LoveGlitchCoffee thanks for creating this issue!  I'm on vacation for the next ~2 weeks and will follow up on this when I get back - just want you to know it isn't being ignored ❤️

**Comment by LoveGlitchCoffee** [comment]
Appreciate the heads up!

**Comment by manwaring** [comment]
Following up on this - you're asking about the url path being different for UPR vs prior sets?  If so like you said that comes directly from https://github.com/the-fab-cube/flesh-and-blood-cards, which in turn comes directly from how LSS is hosting their images on their servers (which is a bit of a mess lol)

**Comment by LoveGlitchCoffee** [comment]
Hey @manwaring , sorry haven't got back on this for a while, been busy 😂 

Yes, I can see that on fab-cube and in the generate .csv, they are setting a lot of incorrect image url paths for UPR going forward, I'll raise an issue in their repo 😛 thanks for taking a look!

Feel free to close if no longer applicable on your side 👍

**Comment by LoveGlitchCoffee** [comment]
oh actually, I just realised that 10 hours ago, `fab-cube` might have just updated their dynasty branch (not merged to develop) to have correct full url in their `card.csv`, unsure if you'll want to update `fab-cards` api to have this field along with `defaultImageName`?

**Comment by manwaring** [comment]
I'm not going to include the LSS-hosted image URLs anymore, I think I stopped providing them with v3 of the library(?)

Two reasons:
- The way I'm using this library on FaBrary I want to minimize package size as much as possible, having the full image URL added a lot of text across all of the cards (+ cards having multiple images)
- I moved away from using the LSS-hosted images on FaBrary because they were very slow to load (uncompressed .pngs + I'm pretty sure they're using a slower storage tier in Google Cloud to save $).  Instead I use the fab-cube project's tools for downloading images + [a script for compressing them](https://github.com/fabrary/images), and then use the same naming convention in this library and that tool to just have imageNames stored here
